### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wangannyi** [kaist-ina/ns2-xpass#7]
Hi, Mr. InhoCho, when I run a large-scale simulation, I have a "Floating point exception (core dumped)" bug. This problem has troubled me for several days. Is there any way to solve it? I really look forward to your reply, thank you very much!

**Comment by inhocho89** [comment]
Can you let us know the experiment environment you have used (ns-2 version, configuration, topology, etc)?
At least without any modification of the master repo, I couldn't reproduce the floating point exception.

**Comment by wangannyi** [comment]
Thank you for your reply! I run the simulation on the Ubuntu18.04.4 operating system. According to "README", the version of ns2 I use is ns2.35, and the script I use is the sample script you posted, "large-scale-fattree.tcl" . I did n’t make any changes, I just wanted to try your script, but it failed, and I was confused.

**Comment by inhocho89** [comment]
ns-allineone-2.35 is known to be incompatible with Ubuntu 18.04. Try with Ubuntu 16.04 or refer to this blog in order to install the ns-2 correctly (https://www.nsnam.com/2018/06/installation-of-ns2-in-ubuntu-1804.html).

**Comment by wangannyi** [comment]
Mr. InhoCho, I forgot to mention a potentially important message. The "Floating point exception (core dumped)" error occurs every time after "data loss detected." Like the following, does this have anything to do with the code?

 Data packet will be dropped.
[194] 0.105339: data loss detected. (expected = 1146101, received = 1278961)
[109] 0.105340: data loss detected. (expected = 661381, received = 766501)
[177] 0.105341: data loss detected. (expected = 1587021, received = 1702361)
[243] 0.105342: data loss detected. (expected = 932941, received = 1045361)
[243] 0.105343: data loss detected. (expected = 932941, received = 1046821)
Floating point exception (core dumped)

**Comment by inhocho89** [comment]
It looks like tcl and tk in ns-allinone-2.35 is not compatible with Ubuntu 18.04. I need some time to fix this issue. In the meantime, can you try with Ubuntu 16.04 and see whether the same problem happens?

**Comment by wangannyi** [comment]
I have updated the version of gcc and g++ according to this blog ( https://www.cnblogs.com/goodswarm/p/10850695.html), which improve my problem. Previous large-scale simulations were only able to run a few hundred traffic. In this way, more flows can be completed and even run successfully until the end in some large-scale scenarios. I am also a little puzzled about it and do not know the specific reasons. and I'm sorry about that I didn't try with Ubuntu16.04, so I can't tell you about it.

**Comment by inhocho89** [comment]
That sounds great, but please note that we haven't verified the current code base with Ubuntu 18.04, further issues might happen.

**Comment by wangannyi** [comment]
Okay, I got it. Thank you for your reply, I will try again on Ubuntu 16.04 next time.
